name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout source code
      - name: Checkout
        uses: actions/checkout@v4

      # Install Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # Enable Flutter web
      - name: Enable Flutter Web
        run: flutter config --enable-web

      # Get packages
      - name: Get dependencies
        run: flutter pub get

      # Build Flutter web app
      - name: Build Web
        run: flutter build web --base-href="/warpdrive_weaver/"

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
